package de.pinneddown.server;

public enum EventType {
    READY_TO_START,
    PLAYER_ENTITY_CREATED,
    MAIN_PHASE_ENDED,
    TOTAL_DISTANCE_CHANGED,
    CARD_PLAYED,
    THREAT_POOL_INITIALIZED,
    ATTACK_PHASE_ENDED,
    ASSIGNMENT_PHASE_ENDED,
    STARSHIP_DEFEATED,
    STARSHIP_ASSIGNED,
    FIGHT_PHASE_ENDED,
    ATTACK_DECK_INITIALIZED,
    JUMP_PHASE_ENDED,
    VICTORY,
    DEFEAT
}
