server:
  port: 9100

spring:
  application:
    name: pinned-down-server

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: false

de:
  pinneddown:
    server:
      version: @project.version@
