# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: maven-setings-action
      uses: s4u/maven-settings-action@v2.2.0
      with:
        servers: '[
          {
            "id": "github-net",
            "username": "npruehs",
            "password": "${{ secrets.PACKAGES_TOKEN }}"
          },
          {
            "id": "github-util",
            "username": "npruehs",
            "password": "${{ secrets.PACKAGES_TOKEN }}"
          },
          {
            "id": "github-test",
            "username": "npruehs",
            "password": "${{ secrets.PACKAGES_TOKEN }}"
          }
        ]'

    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Stage build artifacts
      run: mkdir staging && cp target/*.jar staging

    - name: Upload build artifacts
      uses: actions/upload-artifact@v2
      with:
        name: Package
        path: staging

    - name: Publish package
      run: mvn -B deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
